server:
  port: 8087
springdoc:
  api-docs:
    path: /api-docs

spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:~/test
    username: sa
    password:
    driverClassName: org.h2.Driver
    data: classpath:/db/create.sql
    initialize: true